on:
  push:
    branches:
      - main
  pull_request:
    types: [ assigned, opened, synchronize, reopened, labeled ]
name: ci
permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/checkout@v4
      - run: bun i
      - run: bun run lint
      - run: bun run test
